### PR TITLE
Russian and Ukrainian update 10

### PR DESCRIPTION
**Pull request by DanielProg39**
Updated Russian and Ukrainian translations

### CODE REVIEW

**Comment by Dwynr** [comment]
The app has been completely rewritten and the way we initialize translations aswell. The translation (wording) itself also changed a bit. I can't merge it like this, but I still appreciate your efforts. You can checkout the Readme inside the new i18n folder to see how you can adjust this PR so I can merge it. Thanks :)

**Comment by DanielProg39** [comment]
I understood. I will find out how to contribute

**Comment by DanielProg39** [comment]
I understood. I will find out how to contribute

**Comment by DanielProg39** [comment]
I am working on translations so, please, don't release the app before I open a pull request

**Comment by Dwynr** [comment]
Thank you, we won't release it for another few week probably.

**Pull request closed without merging**
